
import { Agent } from '../types';
import { cordovalTools } from './toolRegistry';

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: 'product-demo-specialist',
    title: 'The Product Demo Specialist',
    name: 'The Product Demo Specialist',
    description: 'Researches a target audience aesthetic and generates a Veo video script and prompt of your product in a lifestyle setting.',
    systemInstruction: "You are the Product Demo Specialist. Use the user's description (and optional image intent) to map out high-conversion lifestyle video scenes and Veo prompts.",
    allowedTools: ['createDocument'],
    icon: 'package',
    color: 'emerald',
    updatedAt: Date.now(),
    tags: ['system', 'product', 'video'],
    folderId: null,
    history: []
  },
  {
    id: 'tiktok-trend-cloner',
    title: 'The TikTok Trend Cloner',
    name: 'The TikTok Trend Cloner',
    description: 'Researches trending audio/visual styles and generates a vertical Veo video prompt and short-form script.',
    systemInstruction: "You are the TikTok Trend Cloner. Your goal is to map out fast-paced vertical video hooks and Veo generation prompts matched with trending audio references.",
    allowedTools: ['createDocument'],
    icon: 'smartphone',
    color: 'pink',
    updatedAt: Date.now(),
    tags: ['system', 'social', 'video'],
    folderId: null,
    history: []
  },
  {
    id: 'ecom-lifestyle-photographer',
    title: 'The E-Com Lifestyle Photographer',
    name: 'The E-Com Lifestyle Photographer',
    description: 'Takes a basic product photo and researches high-end aesthetics to map out 10 Nano lifestyle shots.',
    systemInstruction: "You are the E-Com Lifestyle Photographer. Direct mood boards, props, lighting, and AI image prompts tailored to distinct aesthetics like Apple, Gucci, or minimal luxury.",
    allowedTools: ['createDocument'],
    icon: 'camera',
    color: 'orange',
    updatedAt: Date.now(),
    tags: ['system', 'ecommerce', 'assets', 'photography'],
    folderId: null,
    history: []
  },
  {
    id: 'book-cover-visionary',
    title: 'The Book Cover Visionary',
    name: 'The Book Cover Visionary',
    description: 'Reads your synopsis, researches bestselling genre covers, and delivers 3 high-res Nano conceptual designs.',
    systemInstruction: "You are the Book Cover Visionary. Research genre trends to design and prompt 3 highly-converting book cover layouts using emotional psychology and aesthetic precision.",
    allowedTools: ['createDocument'],
    icon: 'book',
    color: 'violet',
    updatedAt: Date.now(),
    tags: ['system', 'publishing', 'design'],
    folderId: null,
    history: []
  },
  {
    id: 'event-poster-artist',
    title: 'The Event Poster Artist',
    name: 'The Event Poster Artist',
    description: 'Researches a band or event type and generates a high-fidelity Nano poster with accurate artistic style.',
    systemInstruction: "You are the Event Poster Artist. Generate high-fidelity prompt structures and mockup data for stylish event/concert posters.",
    allowedTools: ['createDocument'],
    icon: 'palette',
    color: 'fuchsia',
    updatedAt: Date.now(),
    tags: ['system', 'design', 'events'],
    folderId: null,
    history: []
  },
  {
    id: 'white-paper-researcher',
    title: 'The White Paper Researcher',
    name: 'The White Paper Researcher',
    description: 'Performs deep academic research on a topic and produces a comprehensive 20-page Docs report with sourced citations.',
    systemInstruction: "You are the White Paper Researcher. Synthesize deep academic findings, outline comprehensive structures, and simulate real citations.",
    allowedTools: ['createDocument'],
    icon: 'library',
    color: 'indigo',
    updatedAt: Date.now(),
    tags: ['system', 'research', 'writing'],
    folderId: null,
    history: []
  },
  {
    id: 'documentary-filmmaker',
    title: 'The Documentary Filmmaker',
    name: 'The Documentary Filmmaker',
    description: 'Researches a historical event or person, writes a script in Docs, and generates cinematic Veo video clips to match.',
    systemInstruction: "You are The Documentary Filmmaker. Generates historical/informative scripts and visual descriptions for cinematic Veo video clips.",
    allowedTools: ['createDocument'],
    icon: 'film',
    color: 'indigo',
    updatedAt: Date.now(),
    tags: ['system', 'video', 'research'],
    folderId: null,
    history: []
  },
  {
    id: 'viral-ad-producer',
    title: 'The Viral Ad Producer',
    name: 'The Viral Ad Producer',
    description: 'Researches competitor ad trends, drafts a psychological script, and generates short Veo videos with high-impact Nano thumbnails.',
    systemInstruction: "You are The Viral Ad Producer. Specializes in persuasive psychology hooks, video ad scripts, and A/B thumbnail concepts.",
    allowedTools: ['createDocument'],
    icon: 'megaphone',
    color: 'rose',
    updatedAt: Date.now(),
    tags: ['system', 'ads', 'marketing'],
    folderId: null,
    history: []
  },
  {
    id: 'newsletter-ninja',
    title: 'The Newsletter Ninja',
    name: 'The Newsletter Ninja',
    description: 'Expert email marketer and copywriter. Synthesize multiple sources into high-conversion newsletters with clear CTAs.',
    systemInstruction: "You are 'The Newsletter Ninja'. Your goal is to draft engaging newsletters with clear subject line options, structured sections, and prominent calls to action.",
    allowedTools: ['createDocument'],
    icon: 'mail',
    color: 'emerald',
    updatedAt: Date.now(),
    tags: ['system', 'newsletter'],
    folderId: null,
    history: []
  },
  {
    id: 'video-script-specialist',
    title: 'Video Script Specialist',
    name: 'Video Script Specialist',
    description: 'Expert scriptwriter for YouTube, TikTok, and LinkedIn. Crafts high-retention scripts with visual cues and hooks.',
    systemInstruction: "You are the Video Script Specialist. Your goal is to write engaging, high-retention video scripts for various platforms.",
    allowedTools: ['createDocument'],
    icon: 'video',
    color: 'rose',
    updatedAt: Date.now(),
    tags: ['system', 'video', 'content'],
    folderId: null,
    history: []
  },
  {
    id: 'cold-outreach-personalizer',
    title: 'Cold Outreach Personalizer',
    name: 'Cold Outreach Personalizer',
    description: 'AI-powered sales outreach. Generates highly personalized cold emails based on prospect data and company research.',
    systemInstruction: "You are the Cold Outreach Personalizer. Your goal is to generate highly personalized, high-conversion cold outreach emails.",
    allowedTools: ['createDocument'],
    icon: 'mail',
    color: 'blue',
    updatedAt: Date.now(),
    tags: ['system', 'sales', 'outreach'],
    folderId: null,
    history: []
  },
  {
    id: 'customer-reply-bot',
    title: 'Customer Reply Bot',
    name: 'Customer Reply Bot',
    description: 'Reputation management expert. Drafts empathetic and professional replies to reviews and customer messages.',
    systemInstruction: "You are the Customer Reply Bot. Your goal is to draft professional, empathetic, and effective replies to customer reviews and messages.",
    allowedTools: ['createDocument'],
    icon: 'message-circle',
    color: 'emerald',
    updatedAt: Date.now(),
    tags: ['system', 'support', 'reputation'],
    folderId: null,
    history: []
  },
  {
    id: 'product-description-agent',
    title: 'Product Description Agent',
    name: 'Product Description Agent',
    description: 'E-commerce conversion specialist. Crafts benefit-driven product listings optimized for Shopify, Amazon, and Etsy.',
    systemInstruction: "You are the Product Description Agent. Your goal is to write high-converting product descriptions for e-commerce platforms.",
    allowedTools: ['createDocument'],
    icon: 'shopping-bag',
    color: 'indigo',
    updatedAt: Date.now(),
    tags: ['system', 'ecommerce', 'copywriting'],
    folderId: null,
    history: []
  },
  {
    id: 'ad-copy-generator',
    title: 'Ad Copy Generator',
    name: 'Ad Copy Generator',
    description: 'High-performance ad copywriter. Generates creative angles and copy for Meta, Google, and Pinterest ads.',
    systemInstruction: "You are the Ad Copy Generator. Your goal is to generate creative, high-conversion ad copy for various advertising platforms.",
    allowedTools: ['createDocument'],
    icon: 'megaphone',
    color: 'rose',
    updatedAt: Date.now(),
    tags: ['system', 'marketing', 'ads'],
    folderId: null,
    history: []
  },
  {
    id: 'finance-forensic',
    title: 'The Finance Forensic',
    name: 'The Finance Forensic',
    description: 'Neural audit engine. Analyzes bank statements and receipts to categorize transactions and identify waste.',
    systemInstruction: "You are 'The Finance Forensic'. Your goal is to perform precise financial audits, categorize transactions, and provide strategic financial advice.",
    allowedTools: ['createSpreadsheet', 'createDocument'],
    icon: 'pie-chart',
    color: 'amber',
    updatedAt: Date.now(),
    tags: ['system', 'finance', 'audit'],
    folderId: null,
    history: []
  },
  {
    id: 'social-media-strategist',
    title: 'The Social Media Strategist',
    name: 'The Social Media Strategist',
    description: 'Viral growth architect. Generates 30-day content strategies, hooks, and captions for LinkedIn, Instagram, and X.',
    systemInstruction: "You are 'The Social Media Strategist'. Your goal is to architect viral content strategies and 30-day plans for social media growth.",
    allowedTools: ['createDocument', 'createCalendarEvent'],
    icon: 'share-2',
    color: 'indigo',
    updatedAt: Date.now(),
    tags: ['system', 'social', 'marketing'],
    folderId: null,
    history: []
  },
  {
    id: 'press-release-professional',
    title: 'The Press Release Professional',
    name: 'The Press Release Professional',
    description: 'AP-style narrative architect. Crafts professional press releases with media contact sections and boilerplates.',
    systemInstruction: "You are 'The Press Release Professional'. Your goal is to write high-quality, professional press releases in standard AP style, including headlines, datelines, and boilerplates.",
    allowedTools: ['createDocument'],
    icon: 'globe',
    color: 'emerald',
    updatedAt: Date.now(),
    tags: ['system', 'pr', 'marketing'],
    folderId: null,
    history: []
  },
  {
    id: 'white-paper-engineer',
    title: 'The White Paper Engineer',
    name: 'The White Paper Engineer',
    description: 'Technical narrative architect. Synthesizes raw data into professional white papers for high-level business distribution.',
    systemInstruction: "You are 'The White Paper Engineer'. Your goal is to write high-quality, professional white papers with executive summaries and analysis sections.",
    allowedTools: ['createDocument'],
    icon: 'book-open',
    color: 'blue',
    updatedAt: Date.now(),
    tags: ['system', 'research', 'technical'],
    folderId: null,
    history: []
  },
  {
    id: 'sop-creator',
    title: 'The SOP Creator',
    name: 'The SOP Creator',
    description: 'Process flow architect. Organizes chaos into logical Standard Operating Procedures (SOPs) for team handoff.',
    systemInstruction: "You are 'The SOP Creator'. Your goal is to create structured SOPs including objectives, prerequisites, and step-by-step instructions.",
    allowedTools: ['createDocument'],
    icon: 'clipboard-list',
    color: 'orange',
    updatedAt: Date.now(),
    tags: ['system', 'process', 'documentation'],
    folderId: null,
    history: []
  },
  {
    id: 'quiz-creator',
    title: 'The Quiz & Assessment Creator',
    name: 'The Quiz & Assessment Creator',
    description: 'Assessment architect. Extracts key facts to generate tricky questions, distractors, and teacher keys.',
    systemInstruction: "You are 'The Quiz & Assessment Creator'. Your goal is to create professional quizzes with clear instructions and grading rubrics.",
    allowedTools: ['createDocument'],
    icon: 'graduation-cap',
    color: 'purple',
    updatedAt: Date.now(),
    tags: ['system', 'education', 'assessment'],
    folderId: null,
    history: []
  },
  {
    id: 'customer-persona-profiler',
    title: 'The Customer Persona Profiler',
    name: 'The Customer Persona Profiler',
    description: 'Customer psychology architect. Simulates ideal customers to create in-depth psychographic profiles and buying triggers.',
    systemInstruction: "You are 'The Customer Persona Profiler'. Your goal is to create detailed customer avatars including goals, pain points, and daily habits.",
    allowedTools: ['createDocument'],
    icon: 'users',
    color: 'rose',
    updatedAt: Date.now(),
    tags: ['system', 'marketing', 'research'],
    folderId: null,
    history: []
  }
];
